# To check application names, run `wmctrl -x -l`
# To see xremap debug logs, run `journalctl -u xremap`
modmap:
  - name: Global
    remap:
      CapsLock: CTRL_L
      Super_L:
        held: Super_L
        alone: Muhenkan
        alone_timeout_millis: 750
      Super_R:
        held: Super_R
        alone: Henkan
        alone_timeout_millis: 750

keymap:
  - name: Browser
    application:
      only: [firefox, Navigator.firefox, Google-chrome, Chromium, Vivaldi-stable]
    remap:
      Super-t: C-t
      Super-Shift-t: C-Shift-t
      Super-n: C-n
      Super-Shift-n: C-Shift-n
      Super-w: C-w
      Super-Shift-w: C-Shift-w
      Super-r: C-r
      # Super-l: C-l
      Super-f: C-f
      Super-d: C-d
      Super-y: C-h
      Super-LeftBrace: C-LeftBrace
      Super-RightBrace: C-RightBrace

  - name: macOS like
    application:
      not: [
        URxvt,
        org.wezfurlong.wezterm,
        org.wezfurlong.wezterm.org.wezfurlong.wezterm,
        gnome-terminal-server.Gnome-terminal,
        Alacritty,
        Gvim
      ]
    remap:
      # Cursor
      C-b: Left
      C-f: Right
      C-p: Up
      C-n: Down
      C-h: Backspace
      C-d: Delete
      C-a: Home
      C-e: End
      C-m: Enter
      C-j: Enter
      C-o: [Enter, Left]

      # Copy and paste
      Super-c: C-c
      Super-v: C-v

      Super-a: C-a

  - name: Application specific kill
    application:
      only: [Slack, discord]
    remap:
      Super-q: C-q

  - name: awesome's kill
    remap:
      Super-q:
        launch: ["awesome-client", "client.focus:kill()"]
